//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Studanka.Locales {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Studanka.Locales.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string PageTitle {
            get {
                return ResourceManager.GetString("PageTitle", resourceCulture);
            }
        }
        
        internal static string Introduction1 {
            get {
                return ResourceManager.GetString("Introduction1", resourceCulture);
            }
        }
        
        internal static string Introduction2 {
            get {
                return ResourceManager.GetString("Introduction2", resourceCulture);
            }
        }
        
        internal static string Introduction_3 {
            get {
                return ResourceManager.GetString("Introduction 3", resourceCulture);
            }
        }
        
        internal static string Introduction4 {
            get {
                return ResourceManager.GetString("Introduction4", resourceCulture);
            }
        }
        
        internal static string Introduction1Header {
            get {
                return ResourceManager.GetString("Introduction1Header", resourceCulture);
            }
        }
        
        internal static string Introduction2Header {
            get {
                return ResourceManager.GetString("Introduction2Header", resourceCulture);
            }
        }
        
        internal static string Reservation {
            get {
                return ResourceManager.GetString("Reservation", resourceCulture);
            }
        }
        
        internal static string DrawerAccommodations {
            get {
                return ResourceManager.GetString("DrawerAccommodations", resourceCulture);
            }
        }
        
        internal static string DrawerRestaurant {
            get {
                return ResourceManager.GetString("DrawerRestaurant", resourceCulture);
            }
        }
        
        internal static string DrawerLounge {
            get {
                return ResourceManager.GetString("DrawerLounge", resourceCulture);
            }
        }
        
        internal static string DrawerPriceList {
            get {
                return ResourceManager.GetString("DrawerPriceList", resourceCulture);
            }
        }
        
        internal static string DrawerCancellationConditions {
            get {
                return ResourceManager.GetString("DrawerCancellationConditions", resourceCulture);
            }
        }
        
        internal static string DrawerRelax {
            get {
                return ResourceManager.GetString("DrawerRelax", resourceCulture);
            }
        }
        
        internal static string DrawerMassages {
            get {
                return ResourceManager.GetString("DrawerMassages", resourceCulture);
            }
        }
        
        internal static string DrawerPool {
            get {
                return ResourceManager.GetString("DrawerPool", resourceCulture);
            }
        }
        
        internal static string DrawerSurroundings {
            get {
                return ResourceManager.GetString("DrawerSurroundings", resourceCulture);
            }
        }
        
        internal static string DrawerVillage {
            get {
                return ResourceManager.GetString("DrawerVillage", resourceCulture);
            }
        }
        
        internal static string DrawerPlayground {
            get {
                return ResourceManager.GetString("DrawerPlayground", resourceCulture);
            }
        }
        
        internal static string DrawerRoutes {
            get {
                return ResourceManager.GetString("DrawerRoutes", resourceCulture);
            }
        }
        
        internal static string DrawerContacts {
            get {
                return ResourceManager.GetString("DrawerContacts", resourceCulture);
            }
        }
        
        internal static string Introduction3 {
            get {
                return ResourceManager.GetString("Introduction3", resourceCulture);
            }
        }
        
        internal static string Introduction3Header {
            get {
                return ResourceManager.GetString("Introduction3Header", resourceCulture);
            }
        }
        
        internal static string Promotion {
            get {
                return ResourceManager.GetString("Promotion", resourceCulture);
            }
        }
        
        internal static string AccommodationContent {
            get {
                return ResourceManager.GetString("AccommodationContent", resourceCulture);
            }
        }
    }
}
